### ISSUE TITLE
provide a README file

### ISSUE THREAD

**Issue by rlemon** [xbenjii/Ambience#1]
great project, but it's lacking a README file. that would be very helpful. 

thanks.

**Comment by xbenjii** [comment]
Fixed in f801a8a1a529c2f07bc6eddc75f09ca9d1513365

**Comment by rlemon** [comment]
Sorry, turn around in this project is a joke. I've already found an
alternative that is actually maintained.

**Comment by xbenjii** [comment]
Thanks for the constructive criticism, I'll be looking forward to your future pull requests.
